### ISSUE TITLE
src/riak_sysmon_filter.erl:46: Warning: type gb_tree/0 is deprecated and will be removed in OTP 18.0; use use gb_trees:tree/0 or preferably gb_trees:tree/2

### ISSUE THREAD

**Issue by Pumpapa** [basho/riak_sysmon#15]
Trying to build https://github.com/michaelklishin/riak_core_cowboy_example, I hit upon

src/riak_sysmon_filter.erl:46: Warning: type gb_tree/0 is deprecated and will be removed in OTP 18.0; use use gb_trees:tree/0 or preferably gb_trees:tree/2

Both removing warnings_as_errors or fixing the error as suggested in the warning work. Should I fix it check that in?

**Comment by slfritchie** [comment]
Hi, sorry about the delay.  Basho won't be moving Riak to OTP 18 anytime in the near future.  A PR that would preserve compatibility for R16 as well as avoid the 17 & 18 compilation warning/errors would be happily accepted.  Waiting for Basho to do it will result in a wait of unspecified time, sorry!

**Comment by jlouis** [comment]
Isn't this issue fixed with the work by @cmeiklejohn in commit a2953df86385277 ? It would seem so from my end, in which case this Issue can be closed.

**Comment by cmeiklejohn** [comment]
Yes, this should be resolved.
