### ISSUE TITLE
Missing patch in 2.1.2 which prevents tests from pass

### ISSUE THREAD

**Issue by lemenkov** [basho/riak_sysmon#31]
Unfortunately commit 7203180ecbdf0cb50b1795a3cae4cf8645152e4d is missing in 2.1.2. THis prevents passing tests during build.

See build logs for further details:

http://koji.fedoraproject.org/koji/taskinfo?taskID=13847825

**Comment by hazen** [comment]
@lemenkov Thanks for the note.  I'll try to fix the release.

**Comment by hazen** [comment]
@lemenkov Please try it now.

**Comment by lemenkov** [comment]
@javajolt works now - thanks!

**Comment by lemenkov** [comment]
@javajolt unfortunately this patch should be added to develop branch (and [erhaps some other branches) as well. W/o this patch tests can't be pased in Travis. See pull-request w/o patch:

https://travis-ci.org/lemenkov/riak_sysmon/builds/126930599

And with this patch we've got only one failure during building with long-time obsolete Erlang R15 (see #32)

https://travis-ci.org/lemenkov/riak_sysmon/builds/126930850

**Comment by hazen** [comment]
@lemenkov The work for the next release is begin done on the `develop-2.2` branch at the moment.  I'll talk to @JeetKunDoug about the possibility of merging that over to `develop` since I suspect it's not been done in a while.

**Comment by lemenkov** [comment]
@javajolt @JeetKunDoug ok, got that. Normally I'd expect that every branch compiles cleanly and passes all the tests. But at least the default on should. 

Maybe it would e better just to switch a default branch from develop to develop-2.2
