### ISSUE TITLE
Missing 'sys_dist' table

### ISSUE THREAD

**Issue by chernser** [basho/riak_sysmon#6]
Failed to start riak_core due to error in riak_sysmon: 
15:29:39.860 [error] riak_sysmon_filter:get_node_map: error badarg @ [{ets,match_object,[sys_dist,'_'],[]},{ets,tab2list,1,[{file,"ets.erl"},{line,323}]},{riak_sysmon_filter,get_node_map,0,[{file,"src/riak_sysmon_filter.erl"},{line,360}]},{riak_sysmon_filter,handle_info,2,[{file,"src/riak_sysmon_filter.erl"},{line,249}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,597}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]

The table 'sys_dist' missing in R14B and R15B: 

chernser$ erl 
Erlang R15B (erts-5.9) [source] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V5.9  (abort with ^G)
1> ets:all().
[8207,4110,13,file_io_servers,inet_hosts_file_byaddr,
 inet_hosts_file_byname,inet_hosts_byaddr,inet_hosts_byname,
 inet_cache,inet_db,global_pid_ids,global_pid_names,
 global_names_ext,global_names,global_locks,ac_tab]
2> ets:tab2list(sys_dist).
*\* exception error: bad argument
     in function  ets:match_object/2
        called as ets:match_object(sys_dist,'_')
     in call from ets:tab2list/1 (ets.erl, line 323)
3> 

Do I miss something? I mean should extra applications be started before riak_sysmon? 

Thanks in advance!

**Comment by chernser** [comment]
The root cause of this problem is not started `empd`. Anyway it would be nice to get more reasonable error for this known issue.

**Comment by plainlystated** [comment]
Can you shed a little more light on the solution? I have epmd running, and I still get this error (only when running my eunit tests).

**Comment by slfritchie** [comment]
Bug fix #8 is scheduled for a Riak point release, please see comments there.  Closing.

**Comment by plainlystated** [comment]
FYI (for anyone still hitting this), I got around this by setting the VM's name. In my case, I set it in my code (test harness, dev setup, etc) with this:

```
net_kernel:start([appname_tests, shortnames])
```

Setting it otherwise (vm.args, -name, etc) should work, as well.
